apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-vol
  namespace: monitor
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  rbd:
    monitors:
      - 10.214.160.5:6789
      - 10.214.160.6:6789
      - 10.214.160.7:6789
    pool: kube
    image: grafana
    user: admin
    secretRef:
      name: ceph-secret-admin
    fsType: xfs
    readOnly: false
  # reclaim Policy: Retain, Recycle, Delete
  persistentVolumeReclaimPolicy: Retain
