apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitor
imagePullSecrets:
- name: harbor
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: prometheus-2.0
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitor
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
