apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-vol-2.0
  namespace: monitor
  labels:
    app: prometheus
    version: "2.0"
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.214.160.5:6789
      - 10.214.160.6:6789
      - 10.214.160.7:6789
    path: /kubernetes/prometheus-2.0
    user: admin
    secretRef:
      name: ceph-secret-admin
    readOnly: false
  # reclaim Policy: Retain, Recycle, Delete
  persistentVolumeReclaimPolicy: Retain
