apiVersion: v1
kind: Service
metadata:
  name: zeppelin-{{ .Values.user }}
  namespace: bigdata
  labels:
    app: zeppelin
    user: {{ .Values.user }}
    port: "{{ .Values.port }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.port }}
  selector:
    app: zeppelin
    user: {{ .Values.user }}
