apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
# TODO: set imagePullPolicy to IfNotPresent
    command:
      - sleep
      - "3600"
  restartPolicy: Always
