apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kube-state-metrics.name" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "kube-state-metrics.name" . }}
          servicePort: {{ .Values.service.port }}
